# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c2be9faaf42bf71a630a695997c88ece3f0e095e3e1e8d3c0ffc80504440fd5b2a07d15c0369531aa8559cf062cbfc11a505df88927df7c539915bf840f57f

test:
  secret_key_base: 12bada884785e1f8126e86a091c2fe3d770c7bbbe9aa5e1e6d6cfae8bbc875c5e63dfbfa9bf7088a71b9f337a4aee022da19750f399adc21ae792cdaee49989f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: secure_token

 # <%= ENV["SECRET_KEY_BASE"] %>
